file_paths:
  sfid_file: "input/SFID_file.xlsx"
  sfdc_dump_file: "input/SFDC_dump.xlsx"
  template_file: "input/Weekly_Template.xlsx"
  output_file: "output/Updated_Template.xlsx"

sfid_columns:
  account_name: "Account Name"
  sfid: "SFID"
  created_date: "Created Date"
  opportunity_name: "Opportunity Name"
  opportunity_description: "Opportunity Description"
  tech_practice: "Partner Details"
  activity_type: "Activity Type"
  partner_details: "Partner Details"
  due_date: "Due Date"
  solution_spocs: "Solution SPOCs"
  delivery_lead: "Delivery Lead"
  bid_manager: "Bid Manager"
  proposal_writer: "Proposal Writer"
  orals_spoc: "Orals SPOC"
  status_next_steps: "Status/ Next Steps"
  deal_status: "Deal Status"
  value_m: "$ Value (M)"

sfdc_columns:
  opportunity_id: "Opportunity ID"
  account_name: "Account Name"
  created_date: "Created Date"
  group_sbu: "Group SBU"
  opportunity_owner: "Opportunity Owner"
  stage: "Stage"
  amount_converted: "Amount (converted)"
  type: "Type"
  vertical_practice: "Vertical Practice"
  service_offering: "Service Offering"
  project_type: "Project Type"
  probability: "Probability (%)"
  close_date: "Close Date"
  next_step: "Next Step"
  loss_stage: "Loss Stage"
  lost_reason: "Lost Reason"
  age: "Age"
  bolt_details: "BOLT Details"
  amount_converted_est: "Amount (converted)"

template_columns:
  account_name: 1
  sfid: 2
  created_date: 3
  opportunity_name: 4
  opportunity_description: 5
  group_sbu: 6
  created_by: 7
  stage: 8
  est_deal_value_in_usd: 9
  opp_type: 10
  vertical_practice: 11
  tech_practice: 12
  service_offering: 13
  engagement_type: 14
  probability: 15
  close_date: 16
  next_steps: 17
  loss_stage: 18
  lost_reason: 19
  age: 20
  bolt: 21
  doc_recvd_date: 22
  category: 23
  partner_details: 24
  proposed_sub_date: 25
  domain_practice: 26
  tech_practice_template: 27
  solution_spocs: 28
  delivery_spoc: 29
  proposal_owner: 30
  allocation_proposal_owner_1: 31
  proposal_owner_2: 32
  allocation_proposal_owner_2: 33
  proposal_writer: 34
  allocation_proposal_writer_1: 35
  proposal_writer_2: 36
  allocation_proposal_writer_2: 37
  orals_spoc: 38
  bid_director: 39
  proposal_updates: 40
  proposal_status: 41
  actual_sub_date: 42
  commercial_value: 43
  dsc: 44
  opportunity_stage: 45
  post_sub_activity: 46
  psa_activity_status: 47
  psa_activity_cls_date: 48
  psa_activity_update: 49
  est_deal_value: 50
  large_deal: 51
  sbu_mapping: 52
  created_in_week: 53
  submitted_in_week: 54
  closing_in_week: 55
  psa_comp_in_week: 56
  sub_dt_mapping: 57
  cl_dt_mapping: 58
  psa_comp_dt_mapping: 59
  opp_status: 60
  sb_fy: 61
  sb_qtr: 62
  cl_fy: 63
  cl_qtr: 64
  tcv_brk_up: 65
  bfs_ets: 66
  direct_related: 67
  ob_related_status: 68
  tcv_related_status: 69